#!/usr/bin/env python

import sys

import baker
import subprocess


def shell(cmd, stdin=sys.stdin, stdout=sys.stdout, stderr=sys.stderr):
    return subprocess.call(cmd, stdin=stdin, stdout=stdout, stderr=stderr,
                           shell=True)

@baker.command
def deploy():
    pass

@baker.command(default=True)
def build(environment="dev"):
    """
    Start the server
    """

    # *** NOTE: This is a terrible hack.  It assumes that bauble api is
    # installed in a particular directory, the virtualenv for the bauble api
    # install is in the venv directory and the python version is 3.4
    BAUBLE_API_PATH = "../api"
    shell("jekyll build")
    shell("PYTHONPATH={bauble_api}:{bauble_api}/venv/lib/python3.4/site-packages/ sphinx-build docs _site/docs".format(bauble_api=BAUBLE_API_PATH))


baker.run()
